# Site settings
title: Tirso Peralta
email: tperalta@pm-sol.com
description: > # this means to ignore newlines until "baseurl:"
  I'm an Electronic Engineer, professor at UCV (Universidad Central de Venezuela) who loves programming.
  I've developed webapps with php and mobile apps for Android and iOS.
  On my way to learn ruby and ruby on rails.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://tirsope.me" # the base hostname & protocol for your site
twitter_username: tirsope
github_username:  tirsope

# Build settings
markdown: kramdown
highlighter: pygments
